theme: jekyll-theme-cayman
title: [DF-SSmVEP: Dual Frequency Aggregated Steady-State Motion Visual Evoked Potential Design with Bifold Canonical Correlation Analysis]
description: [we provide supplementary materials for the DF-SSmVEP, Dual Frequency Aggregated Steady-State Motion Visual Evoked Potential Design with Bifold Canonical Correlation Analysis, paper.]
