theme: jekyll-theme-cayman
title: [The title of your site]
description: [Here, we provide supplementary materials for the DF-SSmVEP, Dual Frequency Aggregated Steady-State Motion Visual Evoked Potential Design with Bifold Canonical Correlation Analysis, paper.]
