title: [ Dual Frequency Aggregated Steady-State Motion Visual Evoked Potential Design with Bifold Canonical Correlation Analysis]
description: []
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
